name: Build and Push image to JFrog staging

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  attestations: write
  artifact-metadata: write
  contents: read

jobs:
  build-staging:
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push-jfrog.yaml@77a6b36410ca0a5e9ae2cb5d387e5b34d6f639ef
    with:
      repo_name: kyoto-oci-local-staging
      image_name: agentarena-frontier-model-agent
      platforms: "linux/arm64"
      runner: ubuntu-24.04-arm
      ignore_trivy: false
      run_trivy: true
      context: .
      dockerfile_path: ./docker/Dockerfile
      push: ${{ github.event_name != 'pull_request' }}
